### ISSUE TITLE
A way to add PostCSS plugins

### ISSUE THREAD

**Issue by cerpinn** [itsMapleLeaf/remix-tailwind#5]
The package worked great until I added the `bg-clip-text` class. It didn't work on my browser because the `-webkit` prefix wasn't added. I created a `postcss.config.js` file and added `tailwindcss` and `autoprefixer` to the plugins hoping it would pick up on that but still no luck. 

I think there could be several solutions to this problem: 
https://github.com/itsMapleLeaf/remix-tailwind/blob/fd25cef9d875089badabcd6b5682c3644653e5a9/src/main.ts#L29 
1. Maybe a way for user to add PostCSS plugins when calling `serveTailwindCss`. (e.g. `serveTailwindCss('app/tailwind.css', { postCssPlugins: [autoprefixer] })` - I don't really like this one
2. Look for a `postcss.config.js` file and default to the current config if didn't find any.
3. Accept a path to PostCSS config file. (an alternative to the prior solution - e.g. `serveTailwindCss('app/tailwind.css', { postCssConfig: 'postcss.config.js' })`

Also, autoprefixer isn't the only use case for this. there are other plugins that could be used with TailwindCSS. ([Reference](https://tailwindcss.com/docs/using-with-preprocessors#using-post-css-as-your-preprocessor))

I could submit a PR for this but I wanted to know what you think about it first.

**Comment by itsMapleLeaf** [comment]
Yeah, I actually meant to do this at some point, but ended up never needing to :laughing: though I foresaw the use case anyhow.

I think 3. makes the most sense. 2. isn't very flexible in the case that their config is named or placed somewhere different. Or both, honestly :shrug:
